name: unimol
channels:
  - <unknown>
  - pytorch
  - https://repo.anaconda.com/pkgs/main
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _tflow_select=2.3.0=mkl
  - absl-py=1.3.0=pyhd8ed1ab_0
  - aiohttp=3.8.1=py39h7f8727e_1
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - astor=0.8.1=py39h06a4308_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py39h06a4308_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py39h06a4308_0
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.12.7=ha878542_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=h19f5f5c_2
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39h06a4308_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.2.2=h20bf706_0
  - fftw=3.3.9=h27cfd23_1
  - fontconfig=2.13.1=hef1e5e3_1
  - fonttools=4.33.3=py39hb9d737c_0
  - freetype=2.11.0=h70c0345_0
  - frozenlist=1.2.0=py39h7f8727e_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpcio=1.42.0=py39hce63b2e_0
  - h5py=2.10.0=py39hec9cf62_0
  - hdf5=1.10.6=h3ffc7dd_1
  - icu=58.2=hf484d3e_1000
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=4.11.3=py39h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.15.2=py39h06a4308_0
  - ipython=8.4.0=py39h06a4308_0
  - jedi=0.18.1=py39h06a4308_1
  - joblib=1.1.1=py39h06a4308_0
  - jpeg=9e=h7f8727e_0
  - jupyter_client=7.3.5=py39h06a4308_0
  - jupyter_core=4.11.1=py39h06a4308_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.4.2=py39hf939315_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcblas=3.9.0=12_linux64_mkl
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.20.1=h4ff587b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.4=py39h06a4308_0
  - matplotlib-base=3.5.2=py39hf590b9c_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - multidict=6.0.2=py39h5eee18b_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py39h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py39h06a4308_0
  - numexpr=2.8.3=py39h807cd23_0
  - numpy=1.23.3=py39h14f4228_0
  - numpy-base=1.23.3=py39h31eccc5_0
  - oauthlib=3.2.1=py39h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1s=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.4=py39h6a678d5_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py39hace64e9_1
  - pip=22.2.2=py39h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.20.1=py39h5a03fae_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.4.0=py39h06a4308_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.13=haa1d7c7_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py39h06a4308_0
  - pyzmq=23.2.0=py39h6a678d5_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py39h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=1.1.2=py39h6a678d5_0
  - scipy=1.8.1=py39he49c0e8_0
  - seaborn=0.12.1=py39h06a4308_0
  - setuptools=63.4.1=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.3=h5082296_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tensorboard=2.9.0=py39h06a4308_0
  - tensorboard-data-server=0.6.0=py39hca6d32c_0
  - tensorboard-plugin-wit=1.8.1=py39h06a4308_0
  - tensorflow=2.4.1=mkl_py39h4683426_0
  - tensorflow-base=2.4.1=mkl_py39h43e0292_0
  - tensorflow-estimator=2.6.0=pyh7b7c402_0
  - termcolor=1.1.0=py39h06a4308_1
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.2=py39h5eee18b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=4.3.0=py39h06a4308_0
  - tzdata=2022e=h04d1e81_0
  - unicodedata2=14.0.0=py39hb9d737c_1
  - urllib3=1.26.12=py39h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py39h5eee18b_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.6=h5eee18b_0
  - yarl=1.8.1=py39h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.8.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - art==5.8
    - bytecode==0.14.0
    - contextlib2==21.6.0
    - cython==0.29.33
    - easydict==1.10
    - faiss-cpu==1.7.3
    - fsspec==2023.1.0
    - info-nce-pytorch==0.1.4
    - lightning-utilities==0.7.1
    - ml-collections==0.1.1
    - molvs==0.1.1
    - nvidia-ml-py==11.515.75
    - nvitop==0.11.0
    - prody==2.4.0
    - pycm==3.8
    - pytorch-lightning==1.9.3
    - pyyaml==6.0
    - rdkit-pypi==2022.9.2
    - selfies==2.1.1
    - tensorboardx==2.5.1
    - tokenizers==0.13.2
    - torchmetrics==0.11.1
    - tqdm==4.64.1
    - unicore==0.0.1
    - visualizer==0.0.1
